### ISSUE TITLE
Merge to Master

### ISSUE THREAD

**Issue by austinBailey5624** [JayhawkZombie/EECS581Project#2] opened 2017-01-21 15:55 UTC
Guys we've all worked a lot on our different branches, but its kind of gotten out of hand. The last time all the branches merged with master was November, and the merge issues are only going to get worse the longer we wait.

**Comment by JayhawkZombie** [comment] 2017-01-22 00:01
I have all my work in RefactorLevelCode,  and that's the only branch that's been worked on.

Back when I last wanted to merge with master, there were 36 commits I was behind in, and code was touched that caused countless merge conflicts.  I said screw it and decided to alter everything and get it completely finished.  The issue is that people slammed 75+ commits into master like crazy outside of branches and made it exponentially more difficult to merge anything into master.  There are some series of commits in a row that change only a single file each.

**Comment by JayhawkZombie** [comment] 2017-01-24 00:21
Master is up-to-date and compiles.  The UI is **incomplete** and **buggy**, so don't expect the API to stay the same over the next few days.

**Comment by JayhawkZombie** [comment] 2017-01-25 05:19
Gonna close this.

**Closed as completed by JayhawkZombie** 2017-01-25 05:19 UTC
Labels: enhancement
